global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Main CardVault App
  - job_name: 'cardvault-app'
    static_configs:
      - targets: ['cardvault-app:3000']
    metrics_path: '/api/health'
    scrape_interval: 30s

  # Media Service
  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:3001']
    metrics_path: '/health'
    scrape_interval: 30s

  # API Gateway (nginx)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/health'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s